# Generated by Django 6.0.1 on 2026-03-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="UserType",
            field=models.CharField(
                choices=[
                    ("employee", "Employee"),
                    ("employer", "Employer"),
                    ("admin", "Admin"),
                    ("teamlead", "Team Lead"),
                ],
                max_length=255,
                verbose_name=100,
            ),
        ),
    ]
